<?php
// $Id: zmod.module 10 2008-09-23 00:34:09Z pwolanin $
function zmod_block($op = 'list', $delta = '0', $edit = array()) {
  global $user;

  if ($op == 'list') {
    $blocks = array();
    $blocks['0']['info'] = t('User login/logout link');
    return $blocks;
  }
  elseif ($op == 'view') {
    $block = array();

    switch ($delta) {
      case '0':
        if (!$user->uid) {
          $block['subject'] = '';
          $block['content'] = l(t('Login / Register'), 'user/login', array('attributes' => array('id' => 'toggle-login')));

        }
        else {
          $block['subject'] = '';
          $block['content'] = check_plain($user->name) .' - '. l(t('Log out'), 'logout');
        }
        break;
    }
    return $block;
  }
}

function zmod_menu() {
  $items = array();
  $items['member-list/view'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['member-list/stats'] = array(
    'title' => 'Member stats',
    'page callback' => 'zmod_member_stats',
    'access arguments' => array('access user profiles'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

function zmod_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'view':
      if ($node->type == 'household') {
        $result = db_query(db_rewrite_sql("SELECT n.nid, n.title FROM {node} n JOIN {content_type_member} ctm ON ctm.vid = n.vid WHERE ctm.field_household_nid = %d AND n.status = 1"), $node->nid);
        $list = array();
        while ($m = db_fetch_array($result)) {
          $list[] = l($m['title'], 'node/' . $m['nid']);
        }
        $node->content['zmod_members_at_house'] = array(
          '#value' => '<h3>Members at this address:</h3>' . theme('item_list', $list),
          '#weight' => 100,
        );

      }
      break;

    case 'prepare':
      break;

    
    case 'presave':
      if ($node->type == 'member') {
        // Assign renewal date for updated member.
        $curr = db_fetch_array(db_query("SELECT field_renewal_date_value, field_mem_value FROM {content_type_member} ctm INNER JOIN {node} n ON ctm.vid = n.vid WHERE n.nid = %d", $node->nid));
        if (!$curr || $node->field_mem[0]['value'] > $curr['field_mem_value']) {
          // Don't overwrite user input
          if (empty($node->field_renewal_date[0]['value']) || ($curr && $node->field_renewal_date[0]['value'] == $curr['field_renewal_date_value'])) {
            $node->field_renewal_date[0]['value'] = time();
          }
        }
      }
      break;
  }
}

function zmod_form_alter(&$form, $form_state, $form_id) {

  if ('member_node_form' == $form_id || 'household_node_form' == $form_id)  {
    // Get rid of "- Please choose -" option
    array_shift($form['taxonomy']['9']['#options']);
  }
}

function zmod_init() {
  global $user;

  if (!$user->uid) {
    $data = 
"if (Drupal.jsEnabled) {
  (function($) {
    $(document).ready(function() {
    $('#block-user-0').hide();
    $('#toggle-login').click(function() {
      $('#block-user-0').slideToggle('fast');
      return false;
    });
  });
  })(jQuery);
}";
    drupal_add_js($data, 'inline');
  }
}

function zmod_member_stats() {
  $sql = 
  "SELECT ctm.field_mem_value as membership, COUNT(n.nid) AS num_members, COUNT(DISTINCT(ctm.field_household_nid)) AS num_households 
   FROM {node} n INNER JOIN {content_type_member} ctm ON n.vid = ctm.vid
   WHERE (n.status <> 0) AND (n.type = 'member')
   GROUP BY ctm.field_mem_value
   ORDER BY ctm.field_mem_value DESC";
  $header = array();
  $rows = array();
  $result = db_query($sql);
  while ($row = db_fetch_array($result)) {
    if (!$header) {
      $header = array_keys($row);
    }
    $rows[] = $row;
  }
  $output = '<h3>Aggregate stats</h3>';
  $output .= theme('table', $header, $rows);
  $current = 'M-' . date('y');
  $sql = 
  "SELECT substring(field_district_value, 1, 1) as municipality, COUNT(n.nid) AS num_members, COUNT(DISTINCT(ctm.field_household_nid)) AS num_households 
  FROM {node} n INNER JOIN {content_type_member} ctm ON n.vid = ctm.vid INNER JOIN content_type_household cth ON cth.nid = ctm.field_household_nid INNER JOIN {node} h_node ON h_node.vid = cth.vid
   WHERE (n.status <> 0) AND cth.field_district_value IS NOT NULL AND ctm.field_mem_value = '%s'
   GROUP BY substring(cth.field_district_value, 1, 1)";
  $header = array();
  $rows = array();
  $result = db_query($sql, $current);
  while ($row = db_fetch_array($result)) {
    if (!$header) {
      $header = array_keys($row);
    }
    $rows[] = $row;
  }
  $output .= '<h3>Current year paid full members by municipality</h3>';
  $output .= theme('table', $header, $rows);
  $sql = 
  "SELECT cth.field_district_value as district, COUNT(n.nid) AS num_members, COUNT(DISTINCT(ctm.field_household_nid)) AS num_households 
  FROM {node} n INNER JOIN {content_type_member} ctm ON n.vid = ctm.vid INNER JOIN content_type_household cth ON cth.nid = ctm.field_household_nid INNER JOIN {node} h_node ON h_node.vid = cth.vid
   WHERE (n.status <> 0) AND ctm.field_mem_value = '%s'
   GROUP BY cth.field_district_value
   ORDER BY cth.field_district_value DESC";
  $header = array();
  $rows = array();
  $result = db_query($sql, $current);
  while ($row = db_fetch_array($result)) {
    if (!$header) {
      $header = array_keys($row);
    }
    $rows[] = $row;
  }
    $output .= '<h3>Current year paid full members by district</h3>';
  $output .= theme('table', $header, $rows);
  return $output;
}
