<?php
// $Id: zmod.module 10 2008-09-23 00:34:09Z pwolanin $
function zmod_block($op = 'list', $delta = '0', $edit = array()) {
  global $user;

  if ($op == 'list') {
    $blocks = array();
    $blocks['0']['info'] = t('User login/logout link');
    return $blocks;
  }
  elseif ($op == 'view') {
    $block = array();

    switch ($delta) {
      case '0':
        if (!$user->uid) {
          $block['subject'] = '';
          $block['content'] = l(t('Login / Register'), 'user/login', array('attributes' => array('id' => 'toggle-login')));

        }
        else {
          $block['subject'] = '';
          $block['content'] = check_plain($user->name) .' - '. l(t('Log out'), 'logout');
        }
        break;
    }
    return $block;
  }
}

function zmod_menu() {
  $items = array();

  return $items;
}

function zmod_init() {
  global $user;

  if (!$user->uid) {
    $data = 
"if (Drupal.jsEnabled) {
  (function($) {
    $(document).ready(function() {
    $('#block-user-0').hide();
    $('#toggle-login').click(function() {
      $('#block-user-0').slideToggle('fast');
      return false;
    });
  });
  })(jQuery);
}";
    drupal_add_js($data, 'inline');
  }
}